# Generated by Django 3.1 on 2021-02-11 16:28

from django.db import migrations
import django_otp.fields
import django_otp.plugins.otp_totp.models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_totp', '0002_auto_20190420_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=django_otp.fields.EncryptedHexCharField(default=django_otp.plugins.otp_totp.models.default_key, help_text='A hex-encoded secret key of up to 40 bytes.', max_length=80, validators=[django_otp.plugins.otp_totp.models.key_validator]),
        ),
    ]
