# Generated by Django 3.2.19 on 2023-05-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_email', '0004_throttling'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildevice',
            name='last_generated',
            field=models.DateTimeField(blank=True, help_text='The last time a token was generated for this device.', null=True),
        ),
    ]
